### ISSUE TITLE
UsersActivity (Step 1) code is different from what is on page

### ISSUE THREAD

**Issue by FranciscoBarros** [googlecodelabs/android-persistence#4]
At https://codelabs.developers.google.com/codelabs/android-persistence/#3 there is this paragraph "Next, open the step1 package and review the UsersActivity class, which fetches data from the database using the following code:" and in code box there is " List<User> youngUsers = mDb.userModel().loadAllUsers();"

But in UsersActivity (Step 1) code there is **already** List<User> youngUsers = mDb.userModel().findYoungerThan(35);

Step 1 page at Codelab should be the correct, initially.

**Comment by JoseAlcerreca** [comment]
Yeah, it says "review"
